### ISSUE TITLE
Can this application be installed on Linux ?

### ISSUE THREAD

**Issue by frju365** [LuatixHQ/openex-frontend#1]
Hello,
This application seems to be very interesting, but it seems that your application is for Windows Server whereas most of company use Linux (CentOS and Debian) distros. Is it installable on linux ?

fyi : I use Debian.

frju365

**Comment by SamuelHassine** [comment]
Hello,

OpenEx is not a system application and is compatible with any operating system. The core application required the PHP engine (available on both Linux and Windows) and the PostgreSQL databases engine (idem). The worker required JAVA which is also platform free.

You can find installation documentation here: https://www.openex.io/en/documentation/deployment/

Best regards,
Sam

**Comment by frju365** [comment]
Thank you very much ! And keep doing what you do because it's a very good work ! :+1:
